#Commodity Price Prediction

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [12]:
df = pd.read_csv('/content/commodity_price.csv')
print(df.head())

     State District                  Market                 Commodity  \
0  Gujarat   Amreli                Damnagar         Coriander(Leaves)
1  Gujarat   Amreli             Savarkundla  Bengal Gram(Gram)(Whole)
2  Gujarat   Amreli             Savarkundla               Castor Seed
3  Gujarat    Anand  Khambhat(Grain Market)       Paddy(Dhan)(Common)
4  Gujarat    Anand  Khambhat(Grain Market)       Paddy(Dhan)(Common)

           Variety    Grade Arrival_Date  Min_x0020_Price  Max_x0020_Price  \
0        Coriander      FAQ   19/05/2025             2200             3050
1  Average (Whole)  Non-FAQ   19/05/2025             5305             5525
2      Castor seed      FAQ   19/05/2025             5500             5970
3            Other      FAQ   19/05/2025             1700             2050
4            Paddy      FAQ   19/05/2025             2500             3150

   Modal_x0020_Price
0               2850
1               5390
2               5750
3               1900
4               2900

In [13]:
df.dropna()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price
0,Gujarat,Amreli,Damnagar,Coriander(Leaves),Coriander,FAQ,19/05/2025,2200,3050,2850
1,Gujarat,Amreli,Savarkundla,Bengal Gram(Gram)(Whole),Average (Whole),Non-FAQ,19/05/2025,5305,5525,5390
2,Gujarat,Amreli,Savarkundla,Castor Seed,Castor seed,FAQ,19/05/2025,5500,5970,5750
3,Gujarat,Anand,Khambhat(Grain Market),Paddy(Dhan)(Common),Other,FAQ,19/05/2025,1700,2050,1900
4,Gujarat,Anand,Khambhat(Grain Market),Paddy(Dhan)(Common),Paddy,FAQ,19/05/2025,2500,3150,2900
...,...,...,...,...,...,...,...,...,...,...
2728,West Bengal,Medinipur(W),Ghatal,Bhindi(Ladies Finger),Bhindi,FAQ,19/05/2025,1800,2000,1900
2729,West Bengal,Medinipur(W),Ghatal,Carrot,Carrot,FAQ,19/05/2025,3700,3900,3800
2730,West Bengal,Medinipur(W),Ghatal,Tomato,Local,FAQ,19/05/2025,2000,2200,2100
2731,West Bengal,Sounth 24 Parganas,Baruipur(Canning),Onion,Other,FAQ,19/05/2025,1700,1900,1800
2732,West Bengal,Uttar Dinajpur,Islampur,Rice,Fine,FAQ,19/05/2025,4500,4800,4600

In [15]:
df_encoded = pd.get_dummies(df, columns=[ 'State', 'District', 'Market', 'Commodity', 'Variety' ], drop_first= True)

In [16]:
X = df_encoded[['Min_x0020_Price', 'Max_x0020_Price'] + [col for col in df_encoded.columns if col.startswith(('State_', 'District_', 'Market_', 'Commodity_', 'Variety_', 'Grade_'))]]
y = df_encoded['Modal_x0020_Price']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [19]:
model= LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [20]:
y_pred = model.predict(X_test)

In [21]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Eroor : {mse}')
print(f'r2 Score : {r2}')

Mean Squared Eroor : 82613.3854354025
r2 Score : 0.9951628200635917

#Stock Price Prediction

In [22]:
df2 = pd.read_csv("/content/ADANIPORTS.csv")

In [24]:
df2.head()

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2007-11-27,MUNDRAPORT,EQ,440.00,770.00,1050.00,770.0,959.0,962.90,984.72,27294366,2.687719e+15,NaN,9859619,0.3612
1,2007-11-28,MUNDRAPORT,EQ,962.90,984.00,990.00,874.0,885.0,893.90,941.38,4581338,4.312765e+14,NaN,1453278,0.3172
2,2007-11-29,MUNDRAPORT,EQ,893.90,909.00,914.75,841.0,887.0,884.20,888.09,5124121,4.550658e+14,NaN,1069678,0.2088
3,2007-11-30,MUNDRAPORT,EQ,884.20,890.00,958.00,890.0,929.0,921.55,929.17,4609762,4.283257e+14,NaN,1260913,0.2735
4,2007-12-03,MUNDRAPORT,EQ,921.55,939.75,995.00,922.0,980.0,969.30,965.65,2977470,2.875200e+14,NaN,816123,0.2741

In [36]:
df2=df2.dropna()

In [38]:
df2['Date'] = pd.to_datetime(df2['Date'], errors='coerce')
df2['Year'] = df2['Date'].dt.year
df2['Month'] = df2['Date'].dt.month
df2['Day'] = df2['Date'].dt.day

/tmp/ipython-input-4005218329.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Date'] = pd.to_datetime(df2['Date'], errors='coerce')
/tmp/ipython-input-4005218329.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Year'] = df2['Date'].dt.year
/tmp/ipython-input-4005218329.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Month'] = df2['Date'].dt.month
/tmp/ipython-input-4005218329.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Day'] = df2['Date'].dt.day

In [39]:
df2_encoded = pd.get_dummies(df2, columns= ['Symbol'], drop_first = True)

In [44]:
X2 = df2_encoded[['Prev Close', 'Open','High', 'Low', 'Last', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume', '%Deliverble', 'Year', 'Month', 'Day']]
y2 = df2_encoded['Close']

In [47]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2,y2, test_size = 0.3)

In [48]:
model2 = LinearRegression()
model2.fit(X2_train, y2_train)

LinearRegression()

In [49]:
y2_pred = model.predict(X2_test)

In [50]:
mse2 = mean_squared_error(y2_test, y2_pred)
R2 = r2_score(y2_test, y2_pred)
print(f'Mean Squared Error: {mse2}')
print(f'R2 Score: {R2}')

Mean Squared Error: 12.789199288626884
R2 Score: 0.9991523454801144